"""Deckbuilder workspace model and native JSON serialization."""

from mtg_workbench.deckbuilder.categories import (
    CategoryNormalization,
    CategoryTaxonomy,
    CategoryTaxonomyError,
    load_category_taxonomy,
    normalize_category_key,
)
from mtg_workbench.deckbuilder.role_rules import (
    EvidenceScoreBand,
    RoleDefinition,
    RoleRulesError,
    RoleRuleSet,
    load_role_rules,
    normalize_match_text,
    normalize_role_key,
)
from mtg_workbench.deckbuilder.role_evidence import (
    CardRoleFacts,
    RoleEvidenceMatch,
    match_all_role_evidence,
    match_role_evidence,
)
from mtg_workbench.deckbuilder.card_facts import (
    CardFactsError,
    card_record_to_role_facts,
    records_to_role_facts,
)
from mtg_workbench.deckbuilder.card_fact_lookup import (
    AMBIGUOUS,
    FOUND,
    MISSING,
    CardFactCandidate,
    CardFactLookupError,
    CardFactLookupReport,
    CardFactLookupResult,
    lookup_deck_entry_card_fact,
    lookup_workspace_card_facts,
)
from mtg_workbench.deckbuilder.card_role_pipeline import (
    card_record_to_role_evidence_report,
    card_records_to_role_evidence_reports,
)
from mtg_workbench.deckbuilder.deck_skeleton_report import (
    DeckEntryReference,
    DeckSkeletonReport,
    DuplicateNonbasicWarning,
    build_deck_skeleton_report,
)
from mtg_workbench.deckbuilder.structural_warnings import (
    StructuralWarning,
    StructuralWarningsReport,
    build_structural_warnings_report,
)
from mtg_workbench.deckbuilder.deck_inspection_report import (
    CardFactCoverage,
    DeckInspectionReport,
    DeckInspectionReportError,
    EntryCardRoleReport,
    build_deck_inspection_report,
)
from mtg_workbench.deckbuilder.workspace_view import (
    GROUP_CATEGORY,
    GROUP_COLOR,
    GROUP_COLOR_IDENTITY,
    GROUP_FULL_DECK,
    GROUP_MANA_VALUE,
    GROUP_TYPE,
    GROUP_ZONE,
    SORT_ALPHABET,
    SORT_CATEGORY,
    SORT_COLOR,
    SORT_COLOR_IDENTITY,
    SORT_MANA_VALUE,
    SORT_QUANTITY,
    SORT_TYPE,
    SORT_ZONE,
    WorkspaceViewEntry,
    WorkspaceViewError,
    WorkspaceViewGroup,
    WorkspaceViewProjection,
    build_workspace_view_projection,
)
from mtg_workbench.deckbuilder.import_export import export_plain_text_decklist, import_plain_text_decklist
from mtg_workbench.deckbuilder.mutations import (
    WorkspaceMutationError,
    add_entry,
    decrease_quantity,
    find_entry,
    get_zone_entries,
    increase_quantity,
    list_entries,
    move_category,
    move_zone,
    remove_entry,
    set_commander,
    update_notes,
    update_tags,
)
from mtg_workbench.deckbuilder.models import DeckEntry, DeckWorkspace
from mtg_workbench.deckbuilder.serialization import load_workspace, save_workspace

__all__ = [
    "DeckEntry",
    "DeckWorkspace",
    "DeckEntryReference",
    "DeckSkeletonReport",
    "DuplicateNonbasicWarning",
    "StructuralWarning",
    "StructuralWarningsReport",
    "CardFactCoverage",
    "DeckInspectionReport",
    "DeckInspectionReportError",
    "EntryCardRoleReport",
    "WorkspaceViewEntry",
    "WorkspaceViewError",
    "WorkspaceViewGroup",
    "WorkspaceViewProjection",
    "CategoryNormalization",
    "CategoryTaxonomy",
    "CategoryTaxonomyError",
    "match_role_evidence",
    "match_all_role_evidence",
    "RoleEvidenceMatch",
    "CardRoleFacts",
    "CardFactsError",
    "CardFactCandidate",
    "CardFactLookupError",
    "CardFactLookupReport",
    "CardFactLookupResult",
    "FOUND",
    "MISSING",
    "AMBIGUOUS",
    "GROUP_CATEGORY",
    "GROUP_COLOR",
    "GROUP_COLOR_IDENTITY",
    "GROUP_FULL_DECK",
    "GROUP_MANA_VALUE",
    "GROUP_TYPE",
    "GROUP_ZONE",
    "SORT_ALPHABET",
    "SORT_CATEGORY",
    "SORT_COLOR",
    "SORT_COLOR_IDENTITY",
    "SORT_MANA_VALUE",
    "SORT_QUANTITY",
    "SORT_TYPE",
    "SORT_ZONE",
    "card_record_to_role_evidence_report",
    "card_records_to_role_evidence_reports",
    "card_record_to_role_facts",
    "lookup_deck_entry_card_fact",
    "lookup_workspace_card_facts",
    "build_deck_skeleton_report",
    "build_deck_inspection_report",
    "build_structural_warnings_report",
    "build_workspace_view_projection",
    "normalize_role_key",
    "normalize_match_text",
    "load_role_rules",
    "RoleRuleSet",
    "RoleRulesError",
    "RoleDefinition",
    "EvidenceScoreBand",
    "WorkspaceMutationError",
    "add_entry",
    "decrease_quantity",
    "export_plain_text_decklist",
    "find_entry",
    "get_zone_entries",
    "increase_quantity",
    "import_plain_text_decklist",
    "load_category_taxonomy",
    "list_entries",
    "load_workspace",
    "move_category",
    "move_zone",
    "normalize_category_key",
    "remove_entry",
    "records_to_role_facts",
    "save_workspace",
    "set_commander",
    "update_notes",
    "update_tags",
]
